# Generated by Django 5.2.17 on 2026-09-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_link', models.URLField()),
                ('token', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DurationField(blank=True, null=True)),
                ('max_uniques_cliques', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorter.links')),
            ],
        ),
    ]
